pipeline:
  publish:
    image: plugins/docker
    privileged: true
    settings:
      build_args:
        - gzipLevel=9
        - brotliLevel=11
      registry: git.eseymour.me
      repo: git.eseymour.me/docker/eseymour.me
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
    when:
      branch: main
  publish-dry-run:
    image: plugins/docker
    privileged: true
    settings:
      dry_run: true
      repo: git.eseymour.me/docker/eseymour.me
    when:
      branch:
        exclude: [main]
