pipeline:
  build:
    image: klakegg/hugo:latest
    pull: true
    commands:
      - hugo --baseURL / --minify
  deploy-prod:
    image: tryvium/netlify-cli
    pull: true
    commands:
      - netlify deploy --prod --dir=public --message="$CI_COMMIT_MESSAGE"
    secrets: [netlify_auth_token, netlify_site_id]
    when:
      branch: main
  deploy-draft:
    image: tryvium/netlify-cli
    pull: true
    commands:
      - netlify deploy --dir=public --message="[$CI_COMMIT_BRANCH $CI_BUILD_EVENT] $CI_COMMIT_MESSAGE"
    secrets: [netlify_auth_token, netlify_site_id]
    when:
      branch:
        exclude: [main]
