depends_on:
  - build

when:
  event: push

steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      build_args:
        - gzipLevel=9
        - brotliLevel=11
      registry: git.eseymour.me
      repo: git.eseymour.me/docker/eseymour.me
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      cache_to: type=local,dest=/var/cache/build
      cache_from: type=local,src=/var/cache/build
    volumes:
      - /var/cache/blog:/var/cache/build
    when:
      branch: main

  publish-dry-run:
    image: woodpeckerci/plugin-docker-buildx
    privileged: true
    settings:
      dry_run: true
      repo: git.eseymour.me/docker/eseymour.me
      cache_to: type=local,dest=/var/cache/build
      cache_from: type=local,src=/var/cache/build
    volumes:
      - /var/cache/blog:/var/cache/build
    when:
      branch:
        exclude: [main]
